// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	model "service-courier/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// CourierService is an autogenerated mock type for the CourierService type
type CourierService struct {
	mock.Mock
}

// CreateCourier provides a mock function with given fields: ctx, req
func (_m *CourierService) CreateCourier(ctx context.Context, req *model.CreateCourierRequest) (*model.Courier, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourier")
	}

	var r0 *model.Courier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateCourierRequest) (*model.Courier, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateCourierRequest) *model.Courier); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Courier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.CreateCourierRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllCouriers provides a mock function with given fields: ctx
func (_m *CourierService) GetAllCouriers(ctx context.Context) ([]*model.Courier, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCouriers")
	}

	var r0 []*model.Courier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Courier, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Courier); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Courier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCourier provides a mock function with given fields: ctx, id
func (_m *CourierService) GetCourier(ctx context.Context, id int64) (*model.Courier, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCourier")
	}

	var r0 *model.Courier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Courier, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Courier); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Courier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCourier provides a mock function with given fields: ctx, req
func (_m *CourierService) UpdateCourier(ctx context.Context, req *model.UpdateCourierRequest) (*model.Courier, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCourier")
	}

	var r0 *model.Courier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UpdateCourierRequest) (*model.Courier, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.UpdateCourierRequest) *model.Courier); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Courier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.UpdateCourierRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCourierService creates a new instance of CourierService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourierService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourierService {
	mock := &CourierService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
