// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	model "service-courier/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// CourierRepository is an autogenerated mock type for the CourierRepository type
type CourierRepository struct {
	mock.Mock
}

// CreateCourier provides a mock function with given fields: ctx, courier
func (_m *CourierRepository) CreateCourier(ctx context.Context, courier *model.Courier) error {
	ret := _m.Called(ctx, courier)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourier")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Courier) error); ok {
		r0 = rf(ctx, courier)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllCouriers provides a mock function with given fields: ctx
func (_m *CourierRepository) GetAllCouriers(ctx context.Context) ([]*model.Courier, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCouriers")
	}

	var r0 []*model.Courier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Courier, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Courier); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Courier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCourier provides a mock function with given fields: ctx, id
func (_m *CourierRepository) GetCourier(ctx context.Context, id int64) (*model.Courier, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCourier")
	}

	var r0 *model.Courier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Courier, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Courier); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Courier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCourier provides a mock function with given fields: ctx, courier
func (_m *CourierRepository) UpdateCourier(ctx context.Context, courier *model.Courier) error {
	ret := _m.Called(ctx, courier)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCourier")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Courier) error); ok {
		r0 = rf(ctx, courier)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCourierRepository creates a new instance of CourierRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourierRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourierRepository {
	mock := &CourierRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
