// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	model "service-courier/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// DeliveryRepository is an autogenerated mock type for the DeliveryRepository type
type DeliveryRepository struct {
	mock.Mock
}

// CreateDelivery provides a mock function with given fields: ctx, delivery
func (_m *DeliveryRepository) CreateDelivery(ctx context.Context, delivery *model.Delivery) error {
	ret := _m.Called(ctx, delivery)

	if len(ret) == 0 {
		panic("no return value specified for CreateDelivery")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Delivery) error); ok {
		r0 = rf(ctx, delivery)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteDelivery provides a mock function with given fields: ctx, orderID
func (_m *DeliveryRepository) DeleteDelivery(ctx context.Context, orderID string) error {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDelivery")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FreeCouriers provides a mock function with given fields: ctx, courierIDs
func (_m *DeliveryRepository) FreeCouriers(ctx context.Context, courierIDs []int64) error {
	ret := _m.Called(ctx, courierIDs)

	if len(ret) == 0 {
		panic("no return value specified for FreeCouriers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) error); ok {
		r0 = rf(ctx, courierIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAvailableCourier provides a mock function with given fields: ctx
func (_m *DeliveryRepository) GetAvailableCourier(ctx context.Context) (*model.Courier, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableCourier")
	}

	var r0 *model.Courier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*model.Courier, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *model.Courier); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Courier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAvailableCourierWithMinLoad provides a mock function with given fields: ctx
func (_m *DeliveryRepository) GetAvailableCourierWithMinLoad(ctx context.Context) (*model.Courier, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableCourierWithMinLoad")
	}

	var r0 *model.Courier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*model.Courier, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *model.Courier); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Courier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDeliveryByOrderID provides a mock function with given fields: ctx, orderID
func (_m *DeliveryRepository) GetDeliveryByOrderID(ctx context.Context, orderID string) (*model.Delivery, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetDeliveryByOrderID")
	}

	var r0 *model.Delivery
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Delivery, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Delivery); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Delivery)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOverdueDeliveries provides a mock function with given fields: ctx
func (_m *DeliveryRepository) GetOverdueDeliveries(ctx context.Context) ([]*model.Delivery, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOverdueDeliveries")
	}

	var r0 []*model.Delivery
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Delivery, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Delivery); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Delivery)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDeliveryRepository creates a new instance of DeliveryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeliveryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeliveryRepository {
	mock := &DeliveryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
