// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	model "service-courier/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// DeliveryService is an autogenerated mock type for the DeliveryService type
type DeliveryService struct {
	mock.Mock
}

// AssignCourier provides a mock function with given fields: ctx, req
func (_m *DeliveryService) AssignCourier(ctx context.Context, req *model.AssignRequest) (*model.AssignResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AssignCourier")
	}

	var r0 *model.AssignResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AssignRequest) (*model.AssignResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AssignRequest) *model.AssignResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AssignResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AssignRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnassignCourier provides a mock function with given fields: ctx, req
func (_m *DeliveryService) UnassignCourier(ctx context.Context, req *model.UnassignRequest) (*model.UnassignResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UnassignCourier")
	}

	var r0 *model.UnassignResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UnassignRequest) (*model.UnassignResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.UnassignRequest) *model.UnassignResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UnassignResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.UnassignRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDeliveryService creates a new instance of DeliveryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeliveryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeliveryService {
	mock := &DeliveryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
