// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	order "service-courier/internal/gateway/order"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// OrderGateway is an autogenerated mock type for the OrderGateway type
type OrderGateway struct {
	mock.Mock
}

// GetOrderByID provides a mock function with given fields: ctx, orderID
func (_m *OrderGateway) GetOrderByID(ctx context.Context, orderID string) (*order.ExternalOrder, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 *order.ExternalOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*order.ExternalOrder, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *order.ExternalOrder); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order.ExternalOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrders provides a mock function with given fields: ctx, from
func (_m *OrderGateway) GetOrders(ctx context.Context, from time.Time) ([]*order.ExternalOrder, error) {
	ret := _m.Called(ctx, from)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 []*order.ExternalOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]*order.ExternalOrder, error)); ok {
		return rf(ctx, from)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []*order.ExternalOrder); ok {
		r0 = rf(ctx, from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*order.ExternalOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, from)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderGateway creates a new instance of OrderGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderGateway {
	mock := &OrderGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
